name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest behave behave2cucumber
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Run behave tests and generate report
      run: |
        behave Features --format=json.pretty -o report.json
    - name: Generate cucumber.json from behave report
      run: |
        python -m behave2cucumber -i report.json -o cucumber.json
    - name: Setup Node.js for cucumber-html-reporter
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install and run cucumber-html-reporter
      run: |
        npm install cucumber-html-reporter
        node -e "var reporter = require('cucumber-html-reporter');reporter.generate({theme: 'bootstrap', jsonFile: 'cucumber.json', output: 'cucumber_report.html', reportSuiteAsScenarios: true, scenarioTimestamp: true, launchReport: true});"
    - name: Run unit tests with coverage
      run: |
        pytest --cov=./ --cov-config=.coveragerc --cov-report=html --html=report.html
    - name: Install gh-pages
      run: |
        npm install gh-pages
    - name: Set git identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Deploy reports to GitHub Pages
      run: |
        mkdir report
        mv cucumber_report.html report/cucumber_report.html
        mv report.html report/report.html
        npx gh-pages -d report
